name = input("Enter your name: ")
math = input("Enter Maths marks: ")
science = input("Enter Science marks: ")
english_grammer = input("Enter English grammer marks: ")
hindi = input("Enter Hindi marks: ")
english_literature = input("Enter English Literature marks: ")
sanskrit = input("Enter Sanskrit marks: ")
computer = input("Enter Computer marks: ")
social_science = input("Enter Social Science marks: ")
total = int(math) + int(science) + int(english_grammer) + int(hindi) + int(english_literature) + int(sanskrit) + int(computer) + int(social_science)
percentage = (total / 800) * 100 #Total marks for each subject is 100, total subjects are 8, so total marks is 800
print("---Report Card---")
print("Name: ", name)
print("Maths:", math)
print("Science:", science)
print("English Grammer:", english_grammer)
print("Hindi:", hindi)
print("English Literature:", english_literature)
print("Sanskrit:", sanskrit)
print("Computer:", computer)
print("Social Science:", social_science)
print("Total Marks:", total)
print("Percentage: ", percentage)
print("---Thank You---")
